### ISSUE TITLE
[To-Do] Fixes + Enhancements Needed

### ISSUE THREAD

**Issue by brh55** [udplabs/udp-mobile#2]
I just went through the repo to prepare for demoing, but there are some required fixes or enhancements that need to be done. Here I'll be compiling a list of fixes that need to tackled.

### Application
- [ ] Hide `CustomWebView `Component during Session Token Exchange
- [ ] Fix Back-End / Proxy (Load Profile / Update Profile / Edit Profile / ID Verify)? (display it in app on dashboard config)
- [ ] Update scopes to include ID Token
- [ ] Load Spinner on Profile Page Until All Data is Available

### Terraform
- [ ] Apply a Sign On Policy to Always Request Factor for Step Up MFA Client

### Enhancements
- [ ] Re-adjust Balance after Transaction Success
- [ ] Separate Token View to Display decoded Tokens (ID + Access)
- [ ] Set Threshold (only for $50+, etc) for Step Up MFA -- better demo experience
- [ ] Re-design to Fit Banking App Story
- [ ] Add Transaction History

**Comment by divine514** [comment]
Ok. 
I'm the guy who worked on building this repo. Can I work on fixing those issues? Thank you

**Comment by divine514** [comment]
@brh55 Can I help you to make improvements? Thank you.

**Comment by brh55** [comment]
@divine514 Of course :)

**Comment by divine514** [comment]
Great. Can we have a meeting and discuss the details? @brh55

**Comment by noinarisak** [comment]
hey @divine514! Thanks for offering to help! 🎉  @brh55  and I will coordinate and reach out to your email address that is on your github profile.

**Comment by divine514** [comment]
Thank you!
